package it.polimi.ingsw.am49.controller.gameupdates;

public enum GameUpdateType {
    PLAYER_JOINED_UPDATE,
    PLAYER_LEFT_UPDATE,
    STARTER_CARD_ASSIGNED_UPDATE,
    GAME_STARTED_UPDATE,
    PLAYER_ORDER_UPDATE,
    CHOOSABLE_OBJETIVES_UPDATE,
    HAND_UPDATE,
    HIDDEN_HAND_UPDATE,
    CARD_PLACED_UPDATE,
    DRAW_AREA_UPDATE,
    DRAWABLES_UPDATE, GAME_STATE_UPDATE
}
