package it.polimi.ingsw.am49.model.enumerations;

public enum GameEventType {
    PLAYER_JOINED_EVENT,
    PLAYER_LEFT_EVENT,
    STARTER_CARD_ASSIGNED_EVENT,
    COMMON_OBJECTIVES_DRAWN,
    CHOOSABLE_OBJECTIVES_EVENT,
    PERSONAL_OBJECTIVE_CHOSEN_EVENT,
    PLAYERS_ORDER_SET_EVENT,
    CARD_PLACED_EVENT,
    HAND_UPDATE_EVENT,
    END_GAME,
    DRAW_AREA_EVENT,
    GAME_STATE_CHANGED_EVENT
}
