package it.polimi.ingsw.am49.model.enumerations;

public enum GameEventType {
    PLAYER_JOINED_EVENT,
    PLAYER_LEFT_EVENT,
    COMMON_OBJECTIVES_DRAWN,
    CHOOSABLE_OBJECTIVES_ASSIGNED_EVENT,
    PERSONAL_OBJECTIVE_CHOSEN_EVENT,
    CARD_PLACED_EVENT,
    CARD_DRAWN_EVENT,
    HAND_UPDATE_EVENT,
    END_GAME, GAME_STATE_CHANGED_EVENT
}
